refactor: Inherit from commands.Bot to achieve shared state behaviour
pcparadise/discordbot pull request #26
Opened 2021-05-04 14:09 UTC by lukadd16

This PR addresses #10

This PR adds a more elegant way of achieving the same behaviour as the current SharedState implementation, by creating a sub-class in main.py that inherits from commmands.Bot and adds some additional instance variables (which correlate to the attributes the SharedState class contained).
* Any instance variables that are set in the PCParadiseBot class can be accessed within the same class via `self.var_name` AND can be accessed in other cogs via `self.bot.var_name` (you can see being done in `help.py`).
* This is possible due to the nature of inheriting `commands.Bot` and the fact that each cog's constructor takes in `bot` as an instance variable.

I've largely left the config setup logic untouched and simply relocated the methods from `shared_state.py` and added them as static methods of our child class in `main.py`.

The other methods that I've added to the child class are fairly self-explanatory, though I will point out that I am using the proper [`load_extension()`](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html#discord.ext.commands.Bot.load_extension) method from the library to load all our cogs rather than the current `importlib` implementation where you were loading in the cogs as python modules (which I'm sure has a few negative side-effects).

Last item, you may notice that I'm explicitly defining what [intents](https://discordpy.readthedocs.io/en/stable/intents.html) our bot needs. For simplicity's sake (plus the fact that you'll most likely need them when more features are added), I've subscribed to all of the intents.
* **Note:** when testing the bot and running it in a production environment, make sure you have both of the privileged intents enabled in the [Discord Developer Portal](https://discord.com/developers/applications/). If you haven't done this before, follow this [guide](https://discordpy.readthedocs.io/en/stable/intents.html#privileged-intents) from the Discord.py documentation.

2021-05-07 06:32 UTC, awsomearvinder commented
Appreciated! I like that you used the static typing. :) I'll take a look at the code and review it tomorrow probably.

2021-05-07 21:52 UTC, Ganoosh commented
I really should have dived a bit more into the library before pushing #10, although with that said, I checked over the code. I'll give vinder one last chance to review it, but looks good in my opinion. Thanks for the help

2021-05-07 22:33 UTC, lukadd16 commented
Yeah, no problem :) I've been using discord.py for over half a year now and have developed a good understanding of _almost_ everything the library has to offer, so I'd be happy to help out with the specifics for whatever you are attempting to implement.

2021-05-08 06:01 UTC, awsomearvinder requested changes

2021-05-09 00:30 UTC, lukadd16 commented on src/main.py
> +            print("\nConnection Closed")
Good catch. Now that I look at it again I don't even know why I put in that statement twice.

2021-05-09 00:30 UTC, lukadd16 commented on src/main.py
> +                print(f"FAILED - {extension}")
Got it

2021-05-09 00:34 UTC, lukadd16 commented on src/main.py
> +        self.launch_time = datetime.utcnow()
I explained this in the description of my first commit. Currently the `launch_time` attribute isn't used anywhere else in the codebase, but I thought at some point we would need it to calculate the bot's uptime (i.e. for use in a command).

2021-05-10 12:01 UTC, awsomearvinder commented
I'll merge this in, I tried resolving the merge conflict directly from the github webpage because I didn't have my development enviornment with me - looks like black and pylint didn't like it.

2021-05-10 15:17 UTC, lukadd16 commented
I've resolved the issues in my latest commit

2021-05-10 22:45 UTC, merged